services:
  - type: web
    name: gameasset-backend
    runtime: docker
    dockerfilePath: Dockerfile
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ASPNETCORE_FORWARDEDHEADERS_ENABLED
        value: "true"
      - key: ConnectionStrings__DefaultConnection
        fromDatabase:
          name: gameassetdb
          property: connectionString  # This was the missing property
      - key: ASPNETCORE_URLS
        value: http://*:$PORT
      - key: ASPNETCORE_HTTPS_PORT
        value: "443"
      - key: PORT
        value: "10000"